project:
  type: website
  
website: 
  title: "Delanie Honda"
  site-url: delaniehonda.rbind.io
  description: "Delanie Honda"
  navbar:
    right:
      - href: index.html
        text: "About" 
      - href: portfolio.html
        text: "Portfolio"

format:
  html:
    theme:
    - cosmo
    - theme.scss