---
title: "Portfolio"
from: markdown+emoji
---

## Publications

::: {.publication-card}
**EdTech for Marginalised Learners in Southeast Asia: Perspectives from funders and providers on priorities, design, investment, and scaling considerations**  
Nayasinghe, N., Chrisani, A., Honda, D., & Gunawan, C. J. (2025) *EdTech Hub*

[DOI](https://doi.org/10.53832/edtechhub.1117)
:::

::: {.publication-card}
**The mental health of Asian American adolescents and young adults amid the rise of anti-Asian racism**  
Huynh J, Chien J, Nguyen AT, Honda D, Cho EE, Xiong M, Doan TT and Ngo TD. (2023) *Frontier Public Health*  

[DOI](https://doi.org/10.3389/fpubh.2022.958517)
:::

::: {.publication-card}
**Learning to build back better futures for education: lessons from educational innovation during the COVID-19 pandemic** (Chapter 19)  
Reimers, F. M., Opertti, R. Eds. (2021) *UNESCO International Bureau of Education*

[PDF](https://unesdoc.unesco.org/ark:/48223/pf0000383825)
:::


## Projects

::: {.project-card}
**ICT diagnostic** *(Internal)*\
Partners: *EdTech Hub, Cambodian Ministry of Education, Youth and Sport, UNICEF*\
2025

:bust_in_silhouette: **My role**: Survey & interview design, data analysis, report writing

:pencil: Provided technical assistance to Cambodian ministry department. The report informed the creation of professional development courses for teachers and ministry staff.
:::

::: {.project-card}
**Long Term Outcomes report** *(Internal)*\
Partners: *iMentor*\
2022, 2023

:bust_in_silhouette: **My role**: Project management, data analysis

:pencil: Led the analysis and reporting of post-secondary pathways of US mentoring program. This annual report was used to inform program activities and demonstrate impact of the program.
:::

::: {.project-card}
**When schools shut: gendered impacts of COVID-19 school closures**\
Partners: *Population Council, UNESCO*\
2021

:bust_in_silhouette: **My role**: Data collection, desk review

:pencil: Conducted interviews and conducted a literature review. This report explored the impact of COVID-19 school closures in low-and-middle income countries using a gender lens.

[PDF](https://unesdoc.unesco.org/ark:/48223/pf0000379270)
:::

::: {.project-card}
**Young Asian American Health Survey (YAAHS)**\
Partners: *James Huynh, Jessie Chen, Amy T Nguyen, Emily EunYoung Cho, Maliya Xiong, Tran T Doan, Thoai D Ngo*\
2021

:bust_in_silhouette: **My role**: Survey development, co-author

:pencil: Developed survey instrument and conducted outreach. This project aimed to address the data gap on the mental health and well-being of Asian American youth and adolescents amid increased anti-Asian racism during the COVID-19 pandemic.

[DOI](https://doi.org/10.3389/fpubh.2022.958517)
:::

